queue:
  name: Hosted VS2017
  demands: 
    - msbuild
    - visualstudio
    - vstest

steps:
- task: NuGetToolInstaller@0
  condition: undefined

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(Parameters.solution)'
  condition: undefined

- task: VSBuild@1
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
  condition: undefined

- task: VSTest@2
  inputs:
    testAssemblyVer2: |
          **\$(BuildConfiguration)\*test*.dll
          !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
  condition: undefined

- task: PublishSymbols@1
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
  continueOnError: true
  condition: undefined

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(Parameters.ArtifactName)'
    ArtifactType: 'Container'
  condition: undefined

